services:
    lg.maker:
        class: Lthrt\GridBundle\Model\Maker
        arguments: [ "@doctrine.orm.entity_manager", "@router", "@lg.dumper" ]

    lg.dumper:
        class: Lthrt\GridBundle\Model\Dumper
        arguments: [ "@templating" ]